#----------------------------------------------------------
# Target "list" - lists all found jobs
#----------------------------------------------------------
list:
	@echo "#--------------------------------------------------------------------"
	@echo "# Toolbox generated make targets"
	@echo "#--------------------------------------------------------------------"
	@echo "build        Generates a Makefile w/ all jobs as targets"
	@echo "implement    Implement design and generate bitstream for FPGA"
	@echo "upload       Implement design and generate bitstream for FPGA"
	@echo "sim          Simulate rtl"
	@echo "clean        Cleans directory"
	@echo "#--------------------------------------------------------------------"
.PHONY: list 
#----------------------------------------------------------

#----------------------------------------------------------
# Target "build" 
#----------------------------------------------------------
build: 
	toolbox-cli --color -l info -b build -o toolbox build	
.PHONY: build
#----------------------------------------------------------

#----------------------------------------------------------
# Target "implement" 
#----------------------------------------------------------
implement: 
	toolbox-cli --color -l info -b build -o toolbox implement	
.PHONY: implement
#----------------------------------------------------------

#----------------------------------------------------------
# Target "upload" 
#----------------------------------------------------------
upload: 
	toolbox-cli --color -l info -b build -o toolbox upload	
.PHONY: upload
#----------------------------------------------------------

#----------------------------------------------------------
# Target "sim" 
#----------------------------------------------------------
sim: 
	toolbox-cli --color -l info -b build -o toolbox sim	
.PHONY: sim
#----------------------------------------------------------

#----------------------------------------------------------
# Target "clean" 
#----------------------------------------------------------
clean: 
	rm -rf build *.jou *.log *.pb	
.PHONY: clean
#----------------------------------------------------------

