// File autogenerated by vlog_mem_map python project
// Date Generated: 2021-02-26 12:56:28.193856
// Configuration File: config.yml
// Memory Name: uart_led
// Memory Word Width: 8
// Address Range: 128
`default_nettype none

/****************************/
/* Module: uart_led_mem_map */
/****************************/
module uart_led_mem_map
(
input wire [7:0] uart_led_write_mem [127:0],
output wire [7:0] uart_led_read_mem [127:0],
output wire [3:0] leds0,
output wire [3:0] leds1,
output wire reset
);

/*************************************************/
/* Define Memory and Connect to Flattened Vector */
/*************************************************/
wire [1023:0] flat_uart_led_write_mem;
generate for (genvar i=0; i<128; i=i+1) begin: gen_write_uart_led
    assign flat_uart_led_write_mem[((i+1)*8)-1-:8] = uart_led_write_mem[i];
end endgenerate
wire [1023:0] flat_uart_led_read_mem;
generate for (genvar i=0; i<128; i=i+1) begin: gen_read_uart_led
    assign uart_led_read_mem[i] = flat_uart_led_read_mem[((i+1)*8)-1-:8];
end endgenerate

/**************/
/* Field: LED */
/**************/
// Assigns for register: leds0
assign flat_uart_led_read_mem[`leds0_Sel] = leds0;
assign leds0 = flat_uart_led_write_mem[`leds0_Sel];
// Assigns for register: leds1
assign flat_uart_led_read_mem[`leds1_Sel] = leds1;
assign leds1 = flat_uart_led_write_mem[`leds1_Sel];

/****************/
/* Field: RESET */
/****************/
// Assigns for register: reset
assign flat_uart_led_read_mem[`reset_Sel] = reset;
assign reset = flat_uart_led_write_mem[`reset_Sel];
endmodule
`default_nettype wire