// File autogenerated by vlog_mem_map python project
// Date Generated: 2021-02-16 18:11:56.803563
// Configuration File: config.yml
// Memory Name: uart_led
// Memory Word Width: 8
// Address Range: 128

/**************/
/* Field: LED */
/**************/
`define LED_field_addr 0
// Defines for register "leds"
`define leds_LSbit 0
`define leds_MSbit 7
`define leds_Sel 7:0
`define leds_Width 8
`define leds_LSbit_Addr 0
`define leds_MSbit_Addr 0
`define leds_LSbit_Pos 0
`define leds_MSbit_Pos 7
// Field LED length
`define LED_field_bit_length 8
`define LED_field_byte_length 1

/****************/
/* Field: RESET */
/****************/
`define RESET_field_addr 1
// Defines for register "reset"
`define reset_LSbit 8
`define reset_MSbit 8
`define reset_Sel 8:8
`define reset_Width 1
`define reset_LSbit_Addr 1
`define reset_MSbit_Addr 1
`define reset_LSbit_Pos 0
`define reset_MSbit_Pos 0
// Field RESET length
`define RESET_field_bit_length 1
`define RESET_field_byte_length 1
