# Set target part for vivado (using vc707 evaluation board)
implement.part: "xc7vx485tffg1761-2"
implement.execute: true 

# Set the units for all variable
implement.units.time: "ns"
implement.units.capacitance: "pF"
implement.units.current: "mA"
implement.units.voltage: "V"
implement.units.power: "mW"
implement.units.resistance: "ohm"
implement.units.altitude: "meters"

# Set top level module
implement.top: "blink"

# Files
implement.verilog:
- "src/blink.v"
implement.vhdl: []
implement.xdc: []
#- "src/clocks.xdc"
#- "src/pblocks.xdc"
#- "src/pins.xdc"

implement.config:
  mode: "B_SCAN"
  bank_voltage_select: "GND"
  voltage: 1.8 

implement.clocks:
- name: "clk"
  period: 6.4

implement.ports:
- name: "led"
  package_pin: "AM39" # GPIO_LED_0
  iostandard: "LVCMOS18"
- name: "clk_p"
  package_pin: "AK34" # USER_CLOCK_P
  iostandard: "LVDS"
- name: "clk_n"
  package_pin: "AL34" # USER_CLOCK_N
  iostandard: "LVDS"

upload.bitstream: "build/implement/current/blink.bit"
upload.hw_server.hostname: "localhost"
upload.hw_server.port: 3121
upload.target: "*xilinx_tcf/Digilent/210203A03554A" 
upload.execute: true
upload.query_targets: false 
