// File autogenerated by vlog_mem_map python project
// Date Generated: 2021-02-26 12:56:28.193856
// Configuration File: config.yml
// Memory Name: uart_led
// Memory Word Width: 8
// Address Range: 128

/**************/
/* Field: LED */
/**************/
`define LED_field_addr 0
// Defines for register "leds0"
`define leds0_LSbit 0
`define leds0_MSbit 3
`define leds0_Sel 3:0
`define leds0_Width 4
`define leds0_LSbit_Addr 0
`define leds0_MSbit_Addr 0
`define leds0_LSbit_Pos 0
`define leds0_MSbit_Pos 3
// Defines for register "leds1"
`define leds1_LSbit 4
`define leds1_MSbit 7
`define leds1_Sel 7:4
`define leds1_Width 4
`define leds1_LSbit_Addr 0
`define leds1_MSbit_Addr 0
`define leds1_LSbit_Pos 4
`define leds1_MSbit_Pos 7
// Field LED length
`define LED_field_bit_length 8
`define LED_field_byte_length 1

/****************/
/* Field: RESET */
/****************/
`define RESET_field_addr 1
// Defines for register "reset"
`define reset_LSbit 8
`define reset_MSbit 8
`define reset_Sel 8:8
`define reset_Width 1
`define reset_LSbit_Addr 1
`define reset_MSbit_Addr 1
`define reset_LSbit_Pos 0
`define reset_MSbit_Pos 0
// Field RESET length
`define RESET_field_bit_length 1
`define RESET_field_byte_length 1
