// File autogenerated by vlog_mem_map python project
// Date Generated: 2021-04-27 13:19:51.671517
// Configuration File: config.yml
// Memory Name: uart_i2c_user_clock
// Memory Word Width: 8
// Address Range: 128

/**************/
/* Field: LED */
/**************/
`define LED_field_addr 0
// Defines for register "leds"
`define leds_LSbit 0
`define leds_MSbit 7
`define leds_Sel 7:0
`define leds_Width 8
`define leds_LSbit_Addr 0
`define leds_MSbit_Addr 0
`define leds_LSbit_Pos 0
`define leds_MSbit_Pos 7
// Field LED length
`define LED_field_bit_length 8
`define LED_field_byte_length 1

/****************/
/* Field: RESET */
/****************/
`define RESET_field_addr 1
// Defines for register "reset"
`define reset_LSbit 8
`define reset_MSbit 8
`define reset_Sel 8:8
`define reset_Width 1
`define reset_LSbit_Addr 1
`define reset_MSbit_Addr 1
`define reset_LSbit_Pos 0
`define reset_MSbit_Pos 0
// Field RESET length
`define RESET_field_bit_length 1
`define RESET_field_byte_length 1

/**************/
/* Field: I2C */
/**************/
`define I2C_field_addr 2
// Defines for register "rv0_valid"
`define rv0_valid_LSbit 16
`define rv0_valid_MSbit 16
`define rv0_valid_Sel 16:16
`define rv0_valid_Width 1
`define rv0_valid_LSbit_Addr 2
`define rv0_valid_MSbit_Addr 2
`define rv0_valid_LSbit_Pos 0
`define rv0_valid_MSbit_Pos 0
// Defines for register "rv0_slave_address"
`define rv0_slave_address_LSbit 17
`define rv0_slave_address_MSbit 23
`define rv0_slave_address_Sel 23:17
`define rv0_slave_address_Width 7
`define rv0_slave_address_LSbit_Addr 2
`define rv0_slave_address_MSbit_Addr 2
`define rv0_slave_address_LSbit_Pos 1
`define rv0_slave_address_MSbit_Pos 7
// Defines for register "rv0_reg_address"
`define rv0_reg_address_LSbit 24
`define rv0_reg_address_MSbit 31
`define rv0_reg_address_Sel 31:24
`define rv0_reg_address_Width 8
`define rv0_reg_address_LSbit_Addr 3
`define rv0_reg_address_MSbit_Addr 3
`define rv0_reg_address_LSbit_Pos 0
`define rv0_reg_address_MSbit_Pos 7
// Defines for register "rv0_burst_count"
`define rv0_burst_count_LSbit 32
`define rv0_burst_count_MSbit 33
`define rv0_burst_count_Sel 33:32
`define rv0_burst_count_Width 2
`define rv0_burst_count_LSbit_Addr 4
`define rv0_burst_count_MSbit_Addr 4
`define rv0_burst_count_LSbit_Pos 0
`define rv0_burst_count_MSbit_Pos 1
// Defines for register "rv0_wdata0"
`define rv0_wdata0_LSbit 34
`define rv0_wdata0_MSbit 41
`define rv0_wdata0_Sel 41:34
`define rv0_wdata0_Width 8
`define rv0_wdata0_LSbit_Addr 4
`define rv0_wdata0_MSbit_Addr 5
`define rv0_wdata0_LSbit_Pos 2
`define rv0_wdata0_MSbit_Pos 1
// Defines for register "rv0_wdata1"
`define rv0_wdata1_LSbit 42
`define rv0_wdata1_MSbit 49
`define rv0_wdata1_Sel 49:42
`define rv0_wdata1_Width 8
`define rv0_wdata1_LSbit_Addr 5
`define rv0_wdata1_MSbit_Addr 6
`define rv0_wdata1_LSbit_Pos 2
`define rv0_wdata1_MSbit_Pos 1
// Defines for register "rv0_wdata2"
`define rv0_wdata2_LSbit 50
`define rv0_wdata2_MSbit 57
`define rv0_wdata2_Sel 57:50
`define rv0_wdata2_Width 8
`define rv0_wdata2_LSbit_Addr 6
`define rv0_wdata2_MSbit_Addr 7
`define rv0_wdata2_LSbit_Pos 2
`define rv0_wdata2_MSbit_Pos 1
// Defines for register "rv0_wdata3"
`define rv0_wdata3_LSbit 58
`define rv0_wdata3_MSbit 65
`define rv0_wdata3_Sel 65:58
`define rv0_wdata3_Width 8
`define rv0_wdata3_LSbit_Addr 7
`define rv0_wdata3_MSbit_Addr 8
`define rv0_wdata3_LSbit_Pos 2
`define rv0_wdata3_MSbit_Pos 1
// Defines for register "rv0_rd_wrn"
`define rv0_rd_wrn_LSbit 66
`define rv0_rd_wrn_MSbit 66
`define rv0_rd_wrn_Sel 66:66
`define rv0_rd_wrn_Width 1
`define rv0_rd_wrn_LSbit_Addr 8
`define rv0_rd_wrn_MSbit_Addr 8
`define rv0_rd_wrn_LSbit_Pos 2
`define rv0_rd_wrn_MSbit_Pos 2
// Defines for register "rv1_ready"
`define rv1_ready_LSbit 67
`define rv1_ready_MSbit 67
`define rv1_ready_Sel 67:67
`define rv1_ready_Width 1
`define rv1_ready_LSbit_Addr 8
`define rv1_ready_MSbit_Addr 8
`define rv1_ready_LSbit_Pos 3
`define rv1_ready_MSbit_Pos 3
// Defines for register "rv0_ready"
`define rv0_ready_LSbit 68
`define rv0_ready_MSbit 68
`define rv0_ready_Sel 68:68
`define rv0_ready_Width 1
`define rv0_ready_LSbit_Addr 8
`define rv0_ready_MSbit_Addr 8
`define rv0_ready_LSbit_Pos 4
`define rv0_ready_MSbit_Pos 4
// Defines for register "rv1_valid"
`define rv1_valid_LSbit 69
`define rv1_valid_MSbit 69
`define rv1_valid_Sel 69:69
`define rv1_valid_Width 1
`define rv1_valid_LSbit_Addr 8
`define rv1_valid_MSbit_Addr 8
`define rv1_valid_LSbit_Pos 5
`define rv1_valid_MSbit_Pos 5
// Defines for register "rv1_rdata0"
`define rv1_rdata0_LSbit 70
`define rv1_rdata0_MSbit 77
`define rv1_rdata0_Sel 77:70
`define rv1_rdata0_Width 8
`define rv1_rdata0_LSbit_Addr 8
`define rv1_rdata0_MSbit_Addr 9
`define rv1_rdata0_LSbit_Pos 6
`define rv1_rdata0_MSbit_Pos 5
// Defines for register "rv1_rdata1"
`define rv1_rdata1_LSbit 78
`define rv1_rdata1_MSbit 85
`define rv1_rdata1_Sel 85:78
`define rv1_rdata1_Width 8
`define rv1_rdata1_LSbit_Addr 9
`define rv1_rdata1_MSbit_Addr 10
`define rv1_rdata1_LSbit_Pos 6
`define rv1_rdata1_MSbit_Pos 5
// Defines for register "rv1_rdata2"
`define rv1_rdata2_LSbit 86
`define rv1_rdata2_MSbit 93
`define rv1_rdata2_Sel 93:86
`define rv1_rdata2_Width 8
`define rv1_rdata2_LSbit_Addr 10
`define rv1_rdata2_MSbit_Addr 11
`define rv1_rdata2_LSbit_Pos 6
`define rv1_rdata2_MSbit_Pos 5
// Defines for register "rv1_rdata3"
`define rv1_rdata3_LSbit 94
`define rv1_rdata3_MSbit 101
`define rv1_rdata3_Sel 101:94
`define rv1_rdata3_Width 8
`define rv1_rdata3_LSbit_Addr 11
`define rv1_rdata3_MSbit_Addr 12
`define rv1_rdata3_LSbit_Pos 6
`define rv1_rdata3_MSbit_Pos 5
// Field I2C length
`define I2C_field_bit_length 86
`define I2C_field_byte_length 11
